### ISSUE TITLE
Search repos on GitHub

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#1]
**Please describe the feature you want this project to offer**
Search for GitHub repositories with project tags as parameters from the home screen.
**Describe the solution you'd like**
Implement the `getRepos()` using the GitHub API to search for repositories on GitHub having the tag entered by the user and return the list of repositories having the tag.
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

**Comment by SuvamPrasd** [comment]
I think this issue might be easy for me so could you assign me this particular issue. @C-Harshul

**Comment by C-Harshul** [comment]
> I think this issue might be easy for me so could you assign me this particular issue. @C-Harshul

Sure @SuvamPrasd
