### ISSUE TITLE
Add GitHub action to run dartfmt upon merge with master

### ISSUE THREAD

**Issue by aryan9600** [IEEE-VIT/hacktoberfest-flutter#11]
**Please describe the feature you want this project to offer**
It'd be nice to have consistent and formatted code in the master branch to enhance code readability and navigation.

**Describe the solution you'd like**
Make a GitHub action which would run when a PR gets merged to master. The action would run `dartfmt` to format the code according to the official coding style guideliness.

**Comment by Mastersam07** [comment]
@aryan9600 is there any difference between flutter format and dart format? Also, are you expecting the action to check for formatting issues or to format the code?

I would like to work on this. Can it be assigned to me?

**Comment by Mastersam07** [comment]
Hello, @aryan9600 , sent in a PR #12
