### ISSUE TITLE
Improve the search bar design

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#13]
**Please describe the feature you want this project to offer**
Update the search bar design
**Describe the solution you'd like**
Improve the design of the currently very basic search bar and also make sure to stick to the Hacktober fest theme.

**Comment by Abhishekchauhan089** [comment]
I would like to work on this project

**Comment by SuvamPrasd** [comment]
I am a flutter developer and worked on the various self project. You can check out my GitHub repository. I would like to work on this particular issue.

**Comment by C-Harshul** [comment]
> I am a flutter developer and worked on the various self project. You can check out my GitHub repository. I would like to work on this particular issue. @C-Harshul

@SuvamPrasd As you seem to have more experience with flutter based on the GitHub repositories I'll be assigning this issue to you.Good luck with it.

**Comment by SuvamPrasd** [comment]
Thanks @C-Harshul

**Comment by SuvamPrasd** [comment]
@C-Harshul do I have code for search bar functionality or just the design part only ?
