### ISSUE TITLE
Pixel overflow on opening slimy card.

### ISSUE THREAD

**Issue by IshanDhruv** [IEEE-VIT/hacktoberfest-flutter#19]
**Describe the bug**
Pixel overflow on opening slimy card.

**To Reproduce**

1. Go to 'Contributors page.'
2. Open 'Suvam Prasad's card.
3. See error

**Expected behavior**
No pixel overflow. Name should be clear. Better card design would also be appreciated.

**Comment by r0hnx** [comment]
I would like to work on this issue

**Comment by rkj1998** [comment]
I would like to work on this issue.
