### ISSUE TITLE
Get the list of Contributors

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#2]
**Please describe the feature you want this project to offer**
Get the list of contributors to a project.
**Describe the solution you'd like**
Implement the `getContributors()`  function using the GitHub API get the list of contributors of a particular repository
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

**Comment by meta-boy** [comment]
Can I go ahead with this?

**Comment by C-Harshul** [comment]
> Can I go ahead with this?



> Can I go ahead with this?

Go for it @meta-boy

**Comment by C-Harshul** [comment]
> @C-Harshul Can you clarify how I would get input (repo name and account name)? Or should I not be bothered about it and just write the function.

It will the the repo that the user chooses from the search page. That part hasn't been done yet so maybe for now just add a temporary parameter which would change based on what the user chooses.

**Comment by meta-boy** [comment]
> It will the the repo that the user chooses from the search page. That part hasn't been done yet so maybe for now just add a temporary parameter which would change based on what the user chooses.

Yes for now it's hard-coded, also can you check the PR and merge it if its fine? I switched to `TabBarView` in homepage for performance reasons so it'll be better for others to work with.
