### ISSUE TITLE
Combine search repo functionality and contributors page

### ISSUE THREAD

**Issue by IshanDhruv** [IEEE-VIT/hacktoberfest-flutter#28]
**Please describe the feature you want this project to offer**
The repo selected from the search repo page is not linked with the contributors on the contributors page.

**Describe the solution you'd like**
The contributors on the contributor page should be from a repo selected on the search page. A button could be added to the cards. A transition to the contributors page on clicking the button is also encouraged.

**Comment by InfiniteVerma** [comment]
I'd like to work on this.
