### ISSUE TITLE
Improve the contributor card design

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#4]
**Please describe the feature you want this project to offer**
Trigger a pop-up that allows the user to customize the details to be added in the card.
**Describe the solution you'd like**
The users should be able to customize the card according to themselves and add the card to the contributors list
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

**Comment by uditswaroopa** [comment]
Hi @C-Harshul can you please share your  Flutter SDK Version, so that I can work on the issue
Regards,
Udit Kumar Swaroopa

**Comment by C-Harshul** [comment]
> Hi @C-Harshul can you please share your Flutter SDK Version, so that I can work on the issue
> Regards,
> Udit Kumar Swaroopa

The Flutter SDK version that I'm working on is 1.20.4 of the stable channel. Good luck contributing to this project

**Comment by uditswaroopa** [comment]
I am adding a bit finishing touch that is why I am taking some time, I hope you are not in a hurry

**Comment by C-Harshul** [comment]
> I am adding a bit finishing touch that is why I am taking some time, I hope you are not in a hurry

Not in a hurry but try to finish asap.
