### ISSUE TITLE
Fix: adding loading spinners or animations

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hacktoberfest-flutter#48]
### Description:
Adding loading spinners or any animation while data of repos are fetched from API in the search tab

### To do:
- [x] Ask us to assign the issue
- [x] Once the issue is assigned, you can start working on it
- [x] Create a PR

### Resource:
- [Flutter docs](https://docs.flutter.dev) 

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by apikmeister** [comment]
Hi, can you assign me? I want to work on this.

**Comment by dk-a-dev** [comment]
Hi @apikmeister i am assigning this issue to you make sure to read CONTRIBUTING.md and also stick to note mentioned in the issue. Happy Coding!! Feel free to reach out if help needed:)

**Comment by dk-a-dev** [comment]
I am reviewing the filed PR

**Comment by apikmeister** [comment]
thank you!
