### ISSUE TITLE
Design the search bar 

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#5]
**Please describe the feature you want this project to offer**
Design the search bar to search the tags on GitHub
**Describe the solution you'd like**
Add a Textfield with appropriate decoration to accept a string and store it in a variable that will be used to search GitHub repositories with matching tags
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

**Comment by NivasReddy21** [comment]
I would like to work on this, could you assign this to me?

**Comment by C-Harshul** [comment]
> I would like to work on this, could you assign this to me?

Sure @NivasReddy21
