### ISSUE TITLE
About us page can't load the hacktoberfest Image

### ISSUE THREAD

**Issue by Riktam-Santra** [IEEE-VIT/hacktoberfest-flutter#58]
**Describe the bug**
The HacktoberFest Image on about us tab is a PNG but is being loaded through SvgPicture which gives an XML Parsing exception

**To Reproduce**

1. Open App
2. Go to the About Us Tab
3. See error

**Expected behavior**
The Image Loads normally and is displayed properly

**Screenshots (Optional)**
![Code_9gvSe70eHv](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/f406b50f-40d0-4394-b0d8-e2ad26c68e9a)

**Comment by sosualfred** [comment]
Hello, I would like to work on this issue.

**Comment by dk-a-dev** [comment]
this issue is also duplicate as PR #54 covers it, I am marking it closed
