### ISSUE TITLE
Change UI color to match HacktoberFest's official colors

### ISSUE THREAD

**Issue by Riktam-Santra** [IEEE-VIT/hacktoberfest-flutter#59]
**Describe the bug**
The Background colors on the splash screen and about us screen is `0xff13253d` which doesn't match HacktoberFest's official color used on the splash image which is `0xFF0F0913`

**To Reproduce**
Observe the Colors on the splash screen and the About us screen

1. Start App
2. Observe the colors

**Expected behavior**
The Colors should seamlessly merge with the splash image background

**Screenshots (Optional)**
Previously:
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/eb6f5761-ef93-437d-800e-ee4e15235b6e)
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/74492899-2ed3-43c9-94d4-0a1cb043095f)

After proposed Changes:
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/ec15b6a0-c4f6-44d3-abff-acb5f620cb0a)
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/af6b4bea-3133-4171-ba9a-1724d17a54e5)

**Comment by sosualfred** [comment]
Hello, I would like to work on this issue.

**Comment by sosualfred** [comment]
@Riktam-Santra I guess there's no issues here to fix then.

**Comment by Riktam-Santra** [comment]
@sosualfred don't worry about it, my profile just got updated, seems like this repo has been excluded from hacktoberfest.

**Comment by dk-a-dev** [comment]
@Riktam-Santra this is a duplicate issue check #44 , also the pr for this already exists #53 
I am closing this by marking duplicate, your other PRs are under review

And, wdym by "this repo has been excluded from hacktoberfest."

**Comment by dk-a-dev** [comment]
Duplicate Issue, PR already exists

**Comment by Riktam-Santra** [comment]
@dk-a-dev I checked my hacktoberfest profile just now after submitting the PR, it is directly marked as excluded.
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/144547a1-9907-497c-9655-3f1c2f1a0fc7)

Here's the reason:
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/46277243-74ff-4532-9f39-adebb1bd6492)

**Comment by dk-a-dev** [comment]
We are checking what went wrong
