### ISSUE TITLE
Create design templates 

### ISSUE THREAD

**Issue by C-Harshul** [IEEE-VIT/hacktoberfest-flutter#6]
**Please describe the feature you want this project to offer**
Create design templates for the users to choose  from
**Describe the solution you'd like**
Create a list of design templates that the users will be able to choose from while adding their own cards.
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

**Comment by Zafershah24** [comment]
Hey can I work on this one?

**Comment by C-Harshul** [comment]
> Hey can I work on this one?

Sure @Zafershah24

**Comment by Zafershah24** [comment]
Hey, should I Rebase the Master branch? As my own branch shows "up-to-date"
